export enum actionTypes {
    FETCH_FILMS = 'FETCH_FILMS',
    SORT_FILMS = 'SORT_FILMS',
    FILM_SELECTED = 'FILM_SELECTED',
    SEARCH_FILMS = 'SEARCH_FILMS',
    SET_SEARCH_CRITERIA = 'SET_SEARCH_CRITERIA',
}