export enum actionTypes {
    FETCH_FILMS = 'FETCH_FILMS',
    SORT_FILMS = 'SORT_FILMS',
    SELECTED_FILM = 'SELECTED_FILM',
    SEARCH_FILMS = 'SEARCH_FILMS',
    SET_SEARCH_CRITERIA = 'SET_SEARCH_CRITERIA',
    SET_TYPE_SEARCH = 'SET_TYPE_SEARCH', // delete
    FETCH_FILM = 'FETCH_FILM',
}